"""Generate Unicode 17 Script/Script_Extensions and paired-bracket data."""
from hashlib import sha256
from pathlib import Path
import sys

root = Path(__file__).resolve().parent.parent
directory = Path(sys.argv[1]) if len(sys.argv) > 1 else root / "build/document/deps/unicode-17"
fallback = root / "build/document/deps/SheenBidi-3.0.0/Tools/Unicode"
digests = {
    "Scripts.txt": "9f5e50d3abaee7d6ce09480f325c706f485ae3240912527e651954d2d6b035bf",
    "ScriptExtensions.txt": "ec2107e58825a1586acee8e0911ce18260394ac8b87e535ca325f1ccbeb06bc6",
    "PropertyValueAliases.txt": "64e9a5f76f7a1e8b5a47d6a1f9a26522a251208f5276bdfa1559dac7cf2e827a",
    "BidiBrackets.txt": "dadbaf38a0d0246e5b805bf8725cb81b7c621f93d030595635f5ba2c2f179428",
}
raw, sources = {}, []
for name, digest in digests.items():
    path = directory / name
    if not path.exists():
        path = fallback / name
    data = path.read_bytes()
    assert sha256(data).hexdigest() == digest, path
    assert "17.0" in data[:1000].decode("utf-8"), path
    raw[name] = data.decode("utf-8")
    sources.append(f" * {name} SHA256 {digest}\n")

def records(name):
    for line in raw[name].splitlines():
        line = line.split("#", 1)[0].strip()
        if line:
            yield [field.strip() for field in line.split(";")]

aliases = {}
for fields in records("PropertyValueAliases.txt"):
    if fields[0] == "sc":
        for alias in fields[1:]:
            aliases[alias] = fields[1]
tags = ["Zyyy", "Zinh", "Zzzz"] + sorted(set(aliases.values()) - {"Zyyy", "Zinh", "Zzzz"})
assert len(tags) <= 192
ids = {tag: i for i, tag in enumerate(tags)}
primary = bytearray([2]) * 0x110000
scx = [None] * 0x110000
for name in ("Scripts.txt", "ScriptExtensions.txt"):
    for fields in records(name):
        parts = fields[0].split("..")
        first, last = int(parts[0], 16), int(parts[-1], 16)
        if name == "Scripts.txt":
            primary[first:last + 1] = bytes([ids[aliases[fields[1]]]]) * (last - first + 1)
        else:
            value = tuple(sorted(ids[tag] for tag in fields[1].split()))
            assert value and min(value) >= 3
            scx[first:last + 1] = [value] * (last - first + 1)
sets = [()] + [(i,) for i in range(3, len(tags))]
sets += sorted(set(value for value in scx if value is not None) - set(sets))
assert len(sets) <= 65536
set_ids = {value: i for i, value in enumerate(sets)}
combined = []
for cp in range(0x110000):
    value = scx[cp] if scx[cp] is not None else ((primary[cp],) if primary[cp] >= 3 else ())
    combined.append((primary[cp], set_ids[value]))
rows = []
first = 0
while first < len(combined):
    value = combined[first]
    last = first
    while last + 1 < len(combined) and combined[last + 1] == value:
        last += 1
    if value != (2, 0):
        rows.append((first, last, *value))
    first = last + 1
brackets = [(int(f[0], 16), int(f[1], 16), int(f[2] == "o")) for f in records("BidiBrackets.txt")]
generated = ("/* Unicode 17.0.0: Script, Script_Extensions and Bidi_Paired_Bracket.\n"
    " * Generated by test/generate_unicode_script.py. Unicode License V3.\n"
    " * Copyright Unicode, Inc.; license: ../lib/unicode/LICENSE.\n"
    " * https://www.unicode.org/Public/17.0.0/ucd/\n" + "".join(sources) + " */\n"
    + "static const uint32_t __xgeScriptTags[] = {\n"
    + "".join(f"    0x{int.from_bytes(tag.encode('ascii'), 'big'):08X}u, /* {tag} */\n" for tag in tags) + "};\n"
    + "static const xge_script_set_t __xgeScriptSets[] = {\n"
    + "".join("    {{" + ",".join(f"UINT64_C(0x{sum(1 << (i % 64) for i in value if i // 64 == word):016X})" for word in range(3)) + "}},\n" for value in sets) + "};\n"
    + "static const struct { uint32_t first, last; uint8_t primary; uint16_t extensions; } __xgeScriptRanges[] = {\n"
    + "".join(f"    {{0x{a:04X}u,0x{b:04X}u,{p}u,{s}u}},\n" for a, b, p, s in rows) + "};\n"
    + "static const struct { uint32_t cp, pair; uint8_t open; } __xgeScriptBrackets[] = {\n"
    + "".join(f"    {{0x{cp:04X}u,0x{pair:04X}u,{opened}u}},\n" for cp, pair, opened in brackets) + "};\n").encode("ascii")
target = root / "src/xge_unicode_script_data.inc"
if not target.exists() or target.read_bytes() != generated:
    target.write_bytes(generated)
print(f"{target}: {len(tags)} scripts, {len(sets)} sets, {len(rows)} ranges, {len(brackets)} brackets")
