"""Pin Unicode 17 default-ignorable coverage used by ordered font fallback."""
from hashlib import sha256
from pathlib import Path
import re
import sys

root = Path(__file__).resolve().parent.parent
source = Path(sys.argv[1]) if len(sys.argv) > 1 else root / "build/document/deps/SheenBidi-3.0.0/Tools/Unicode/DerivedCoreProperties.txt"
data = source.read_bytes()
text = data.decode("utf-8")
assert text.startswith("# DerivedCoreProperties-17.0.0.txt")
rows = []
for line in text.splitlines():
    match = re.match(r"^([0-9A-F]+)(?:\.\.([0-9A-F]+))?\s*; Default_Ignorable_Code_Point\s", line)
    if match:
        rows.append((int(match[1],16),int(match[2] or match[1],16)))
assert len(rows) == 27 and all(rows[i-1][1] < rows[i][0] for i in range(1,len(rows)))
target = root / "src/xge_text_ignorable_data.inc"
generated = ("/* Unicode 17.0.0 DerivedCoreProperties.txt Default_Ignorable_Code_Point.\n"
    " * Generated by test/generate_font_ignorable.py; Unicode License V3.\n"
    " * Copyright Unicode, Inc. License: ../lib/unicode/LICENSE.\n"
    " * https://www.unicode.org/Public/17.0.0/ucd/DerivedCoreProperties.txt\n"
    f" * Source SHA256: {sha256(data).hexdigest()} */\n"
    "static const struct { uint32_t first,last; } __xgeOtIgnorableRanges[] = {\n"
    + "".join(f"    {{0x{first:04X}u,0x{last:04X}u}},\n" for first,last in rows) + "};\n").encode("ascii")
if not target.exists() or target.read_bytes() != generated:
    target.write_bytes(generated)
print(target)
