"""Generate Joining_Type=T data from the pinned Unicode 17 database."""
from hashlib import sha256
from pathlib import Path

root = Path(__file__).resolve().parent.parent
source = root / "test_xui/data/unicode-17/DerivedJoiningType.txt"
digest = "f39ebe974825d6736aee15582250307aa532b2cfab3caf3f86bd23fddc9c5c4d"
data = source.read_bytes()
assert sha256(data).hexdigest() == digest
ranges = []
for line in data.decode("utf-8").splitlines():
    fields = line.split("#", 1)[0].strip().split(";")
    if len(fields) == 2 and fields[1].strip() == "T":
        bounds = fields[0].strip().split("..")
        ranges.append((int(bounds[0], 16), int(bounds[-1], 16)))
ranges.sort()
merged = []
for first, last in ranges:
    if merged and first == merged[-1][1] + 1:
        merged[-1] = (merged[-1][0], last)
    else:
        assert not merged or first > merged[-1][1]
        merged.append((first, last))
text = ("/* Generated by test/generate_unicode_joining.py; Unicode 17.0.0.\n"
        f" * DerivedJoiningType.txt SHA256 {digest}\n"
        " * Unicode data license: lib/unicode/LICENSE. */\n"
        "static const struct { uint32_t first, last; } __xgeJoiningTransparentRanges[] = {\n")
text += "".join(f"    {{0x{first:x}u, 0x{last:x}u}},\n" for first, last in merged)
text += "};\n"
target = root / "src/xge_unicode_joining_data.inc"
if not target.exists() or target.read_bytes() != text.encode():
    target.write_bytes(text.encode())
print(f"Unicode 17 Joining_Type=T: {len(merged)} ranges, {sum(b-a+1 for a,b in merged)} scalars")
