"""Generate shared Unicode 17 grapheme properties from pinned official data."""
from hashlib import sha256
from pathlib import Path
import sys

root = Path(__file__).resolve().parent.parent
directory = Path(sys.argv[1]) if len(sys.argv) > 1 else root / "build/document/deps/unicode-17"
core = directory / "DerivedCoreProperties.txt"
if not core.exists():
    core = root / "build/document/deps/SheenBidi-3.0.0/Tools/Unicode/DerivedCoreProperties.txt"
digests = {
    "GraphemeBreakProperty.txt": "d6b51d1d2ae5c33b451b7ed994b48f1f4dc62b2272a5831e7fd418514a6bae89",
    "DerivedCoreProperties.txt": "24c7fed1195c482faaefd5c1e7eb821c5ee1fb6de07ecdbaa64b56a99da22c08",
    "emoji-data.txt": "2cb2bb9455cda83e8481541ecf5b6dfda66a3bb89efa3fa7c5297eccf607b72b",
}
names = ["Other", "CR", "LF", "Control", "Extend", "ZWJ", "Regional_Indicator", "Prepend", "SpacingMark", "L", "V", "T", "LV", "LVT"]
incb = {"Consonant": 1, "Extend": 2, "Linker": 3}
properties = bytearray(0x110000)
sources = []
for path, kind in [(directory / "GraphemeBreakProperty.txt", "GCB"), (core, "InCB"), (directory / "emoji-data.txt", "EP")]:
    data = path.read_bytes()
    assert sha256(data).hexdigest() == digests[path.name], path
    text = data.decode("utf-8")
    assert "17.0" in text[:1000], path
    sources.append(f" * {path.name} SHA256 {sha256(data).hexdigest()}\n")
    for line in text.splitlines():
        line = line.split("#", 1)[0].strip()
        if not line:
            continue
        fields = [field.strip() for field in line.split(";")]
        if kind == "InCB" and fields[1] != "InCB":
            continue
        if kind == "EP" and fields[1] != "Extended_Pictographic":
            continue
        parts = fields[0].split("..")
        first, last = int(parts[0], 16), int(parts[-1], 16)
        value = names.index(fields[1]) if kind == "GCB" else incb[fields[2]] << 4 if kind == "InCB" else 64
        for cp in range(first, last + 1):
            properties[cp] |= value
rows = []
first = 0
while first < len(properties):
    value = properties[first]
    last = first
    while last + 1 < len(properties) and properties[last + 1] == value:
        last += 1
    if value:
        rows.append((first, last, value))
    first = last + 1
generated = ("/* Unicode 17.0.0: GCB, InCB and Extended_Pictographic.\n"
    " * Generated by test/generate_unicode_grapheme.py. Unicode License V3.\n"
    " * Copyright Unicode, Inc.; license: ../lib/unicode/LICENSE.\n"
    " * https://www.unicode.org/Public/17.0.0/ucd/\n" + "".join(sources) + " */\n"
    "static const struct { uint32_t first, last; uint8_t property; } __xgeGraphemeRanges[] = {\n"
    + "".join(f"    {{0x{a:04X}u,0x{b:04X}u,{p}u}},\n" for a, b, p in rows) + "};\n").encode("ascii")
target = root / "src/xge_unicode_grapheme_data.inc"
if not target.exists() or target.read_bytes() != generated:
    target.write_bytes(generated)
print(f"{target}: {len(rows)} disjoint combined ranges")
