#ifndef XUI_DOCUMENT_LIST_SPLIT_SOURCE_SAMPLES_H
#define XUI_DOCUMENT_LIST_SPLIT_SOURCE_SAMPLES_H
static const struct { const char* input; const char* expected; unsigned offset; } document_list_split_source_samples[] = {
    {"- > 7) [x] abcd\n  >    \n  >    [unused]: /raw 'Title'\n",
        "- > 7) [x] ab\n  >    \n  > 8) [ ] cd\n  >    \n  >    [unused]: /raw 'Title'\n", 2},
    {"+ abcd\n\n  [unused]: /raw 'Title'\n",
        "+ ab\n  \n+ cd\n\n  [unused]: /raw 'Title'\n", 2},
    {"> 12) **abcd**\r\n>     \r\n>     [unused]: <raw> \"Title\"\r\n",
        "> 12) **ab**\r\n>     \r\n> 13) **cd**\r\n>     \r\n>     [unused]: <raw> \"Title\"\r\n", 2},
    {"- outer\n  + abcd\n\n    [unused]: /raw 'Title'\n  + tail &amp; raw\n",
        "- outer\n  + ab\n    \n  + cd\n\n    [unused]: /raw 'Title'\n  + tail &amp; raw\n", 2},
    {"- [unused]: /raw 'Title'\n\n  abcd\n",
        "- [unused]: /raw 'Title'\n\n  ab\n  \n- cd\n", 2},
    {"> - intro &amp; raw\n>\n>   abcd\n>\n>   [unused]: /raw 'Title'\n> - tail &amp; raw\n",
        "> - intro &amp; raw\n>\n>   ab\n>   \n> - cd\n>\n>   [unused]: /raw 'Title'\n> - tail &amp; raw\n", 2},
    {"-\t>\t7)\t[x]\tabcd\n \t>\t\t\n \t>\t\t[unused]: /raw 'Title'\n",
        "-\t>\t7)\t[x]\tab\n \t>\t  \t\n \t>\t8)\t[ ]\tcd\n \t>\t\t\n \t>\t\t[unused]: /raw 'Title'\n", 2},
    {"> 99) abcd\r\n>     efgh\r\n>     \r\n>     [unused]: /raw 'Title'\r\n",
        "> 99) ab\r\n>     \r\n> 100) cd\r\n>      efgh\r\n>      \r\n>      [unused]: /raw 'Title'\r\n", 2},
    {"+ abcd\n\n  after &amp; raw\n\n  [unused]: /raw 'Title'\n+ tail &amp; raw\n",
        "+ ab\n  \n+ cd\n\n  after &amp; raw\n\n  [unused]: /raw 'Title'\n+ tail &amp; raw\n", 2},
    {"+ a&#98;cd\n\n  [unused]: /raw 'Title'\n\n  [unused]: /second 'Duplicate'\n",
        "+ ab\n  \n+ cd\n\n  [unused]: /raw 'Title'\n\n  [unused]: /second 'Duplicate'\n", 2},
    {"7) before &amp; raw\n99) abcd\n\n    [unused]: /raw 'Title'\n88) tail &amp; raw\n",
        "7) before &amp; raw\n99) ab\n    \n9) cd\n\n   [unused]: /raw 'Title'\n88) tail &amp; raw\n", 2},
    {"- [x] abcd\n\n  [unused]: /raw 'Title'\n",
        "- [x] \n  \n- [ ] abcd\n\n  [unused]: /raw 'Title'\n", 0},
    {"- [x] abcd\n\n  [unused]: /raw 'Title'\n",
        "- [x] abcd\n  \n- [ ] \n\n  [unused]: /raw 'Title'\n", 4},
    {"+ \xce\xb1\xce\xb2" "abcd\r\r  [unused]: /raw 'Title'\r",
        "+ \xce\xb1\xce\xb2" "ab\r  \r+ cd\r\r  [unused]: /raw 'Title'\r", 2},
    {"\xef\xbb\xbf+ abcd\n\n  [unused]: /raw 'Title'\n",
        "\xef\xbb\xbf+ ab\n  \n+ cd\n\n  [unused]: /raw 'Title'\n", 2},
    {"* abcd", "* ab\n* cd", 2},
    {"+ # abcd\n\n  [unused]: /raw 'Title'\n",
        "+ # ab\n  \n+ cd\n\n  [unused]: /raw 'Title'\n", 2},
    {"before &amp; raw\n\n+ [abcd][ref]\n\n  [ref]: /raw 'Title'\n\nafter &amp; raw\n",
        "before &amp; raw\n\n+ [ab](<\\/raw> \"Title\")\n  \n+ [cd](<\\/raw> \"Title\")\n\n  [ref]: /raw 'Title'\n\nafter &amp; raw\n", 2},
    {"1) before\n99) abcd\n\n\t[unused]: /raw 'Title'\n88) tail\n",
        "1) before\n99) ab\n    \n3) cd\n\n   [unused]: /raw 'Title'\n88) tail\n", 2},
    {"1) before\n999999999) abcd\n\n           [unused]: /raw 'Title'\n9) tail\n",
        "1) before\n999999999) ab\n           \n3) cd\n\n   [unused]: /raw 'Title'\n9) tail\n", 2},
    {"99) abcd\n\n    > quote &amp; raw\n\n    [unused]: /raw 'Title'\n",
        "99) ab\n    \n100) cd\n\n     > quote &amp; raw\n\n     [unused]: /raw 'Title'\n", 2},
    {"99) abcd\n\n    [unused]: /raw 'First\n    Second'\n",
        "99) ab\n    \n100) cd\n\n     [unused]: /raw 'First\n     Second'\n", 2},
    {"> 99) abcd\r\n>     \r\n>     [un\r\n>     used]: /raw \"First\r\n>     Second\"\r\n",
        "> 99) ab\r\n>     \r\n> 100) cd\r\n>      \r\n>      [un\r\n>      used]: /raw \"First\r\n>      Second\"\r\n", 2},
    {"1) before\n99) abcd\n\n    [unused]:\n    /raw\n    'First\n    Second'\n88) tail\n",
        "1) before\n99) ab\n    \n3) cd\n\n   [unused]:\n   /raw\n   'First\n   Second'\n88) tail\n", 2},
    {"99) abcd\n\n\t[unused]: /raw 'First\n\tSecond'\n\nAfter [use][unused]\n",
        "99) ab\n    \n100) cd\n\n\t [unused]: /raw 'First\n\t Second'\n\nAfter [use][unused]\n", 2},
    {"99) abcd\n\n    [unused]: /first 'First\n    Second'\n\n    [unused]: /other \"Other\n    Lines\"\n",
        "99) ab\n    \n100) cd\n\n     [unused]: /first 'First\n     Second'\n\n     [unused]: /other \"Other\n     Lines\"\n", 2},
    {"---\n[fake]: /ignore 'First\nSecond'\n---\n\n99) abcd\n\n    [unused]: /raw 'First\n    Second'\n",
        "---\n[fake]: /ignore 'First\nSecond'\n---\n\n99) ab\n    \n100) cd\n\n     [unused]: /raw 'First\n     Second'\n", 2},
    {"\xef\xbb\xbf" "99) abcd\r\r    [un\r    used]: /raw 'First\r    Second'\r",
        "\xef\xbb\xbf" "99) ab\r    \r100) cd\r\r     [un\r     used]: /raw 'First\r     Second'\r", 2},
    {"- > 99) [x] abcd\n  >     \n  >     [unused]: /raw 'First\n  >     Second'\n",
        "- > 99) [x] ab\n  >     \n  > 100) [ ] cd\n  >      \n  >      [unused]: /raw 'First\n  >      Second'\n", 2},
    {"98) abcd\n\n    [un\n    used]: /raw 'First\n    Second'\n",
        "98) ab\n    \n99) cd\n\n    [un\n    used]: /raw 'First\n    Second'\n", 2},
    {"99) abcd\n\n    [unused]: /raw 'First\n    Second'\n\n    [empty]: /empty ''\n\n    [absent]: /none\n",
        "99) ab\n    \n100) cd\n\n     [unused]: /raw 'First\n     Second'\n\n     [empty]: /empty ''\n\n     [absent]: /none\n", 2},
    {"1) before\n99) abcd\n\n\t[unused]: /raw 'First\n\tSecond'\n\nAfter [use][unused]\n",
        "1) before\n99) ab\n    \n3) cd\n\n   [unused]: /raw 'First\n   Second'\n\nAfter [use][unused]\n", 2},
    {"99) abcd\n\n    [unused]: /raw 'First\n    Second'\n\n[^note]: unused &amp; raw\n",
        "99) ab\n    \n100) cd\n\n     [unused]: /raw 'First\n     Second'\n\n[^note]: unused &amp; raw\n", 2}
};
#endif
