#ifndef XUI_CONFIG_H
#define XUI_CONFIG_H
#include "xge_config.h"

/* Per-control switches. Dependencies are listed in tools/features.json. */
#ifndef XUI_ENABLE_ACCORDION
#define XUI_ENABLE_ACCORDION (XGE_ENABLE_XUI && XGE_BUILD_PROFILE != XGE_PROFILE_UI_MIN)
#endif
#ifndef XUI_ENABLE_BREADCRUMB
#define XUI_ENABLE_BREADCRUMB (XGE_ENABLE_XUI && XGE_BUILD_PROFILE != XGE_PROFILE_UI_MIN)
#endif
#ifndef XUI_ENABLE_BUTTON
#define XUI_ENABLE_BUTTON (XGE_ENABLE_XUI)
#endif
#ifndef XUI_ENABLE_CANVAS
#define XUI_ENABLE_CANVAS (XGE_ENABLE_XUI && XGE_BUILD_PROFILE != XGE_PROFILE_UI_MIN)
#endif
#ifndef XUI_ENABLE_CAROUSEL
#define XUI_ENABLE_CAROUSEL (XGE_ENABLE_XUI && XGE_BUILD_PROFILE != XGE_PROFILE_UI_MIN)
#endif
#ifndef XUI_ENABLE_CASCADER
#define XUI_ENABLE_CASCADER (XGE_ENABLE_XUI && XGE_BUILD_PROFILE != XGE_PROFILE_UI_MIN)
#endif
#ifndef XUI_ENABLE_CHART
#define XUI_ENABLE_CHART (XGE_ENABLE_XUI && XGE_BUILD_PROFILE != XGE_PROFILE_UI_MIN)
#endif
#ifndef XUI_ENABLE_CHECKBOX
#define XUI_ENABLE_CHECKBOX (XGE_ENABLE_XUI && XGE_BUILD_PROFILE != XGE_PROFILE_UI_MIN)
#endif
#ifndef XUI_ENABLE_CHECK_CARD
#define XUI_ENABLE_CHECK_CARD (XGE_ENABLE_XUI && XGE_BUILD_PROFILE != XGE_PROFILE_UI_MIN)
#endif
#ifndef XUI_ENABLE_CODE_EDIT
#define XUI_ENABLE_CODE_EDIT (XGE_ENABLE_XUI && XGE_BUILD_PROFILE != XGE_PROFILE_UI_MIN)
#endif
#ifndef XUI_ENABLE_COLOR_PICKER
#define XUI_ENABLE_COLOR_PICKER (XGE_ENABLE_XUI && XGE_BUILD_PROFILE != XGE_PROFILE_UI_MIN)
#endif
#ifndef XUI_ENABLE_COMBOBOX
#define XUI_ENABLE_COMBOBOX (XGE_ENABLE_XUI && XGE_BUILD_PROFILE != XGE_PROFILE_UI_MIN)
#endif
#ifndef XUI_ENABLE_DATE_PICKER
#define XUI_ENABLE_DATE_PICKER (XGE_ENABLE_XUI && XGE_BUILD_PROFILE != XGE_PROFILE_UI_MIN)
#endif
#ifndef XUI_ENABLE_DOCK_PANEL
#define XUI_ENABLE_DOCK_PANEL (XGE_ENABLE_XUI && XGE_BUILD_PROFILE != XGE_PROFILE_UI_MIN)
#endif
#ifndef XUI_ENABLE_DOCUMENT
#define XUI_ENABLE_DOCUMENT (XGE_ENABLE_XUI && XGE_BUILD_PROFILE != XGE_PROFILE_UI_MIN)
#endif
#ifndef XUI_ENABLE_DOCUMENT_EDITOR
#define XUI_ENABLE_DOCUMENT_EDITOR (XGE_ENABLE_XUI && XGE_BUILD_PROFILE != XGE_PROFILE_UI_MIN)
#endif
#ifndef XUI_ENABLE_DOCUMENT_VIEW
#define XUI_ENABLE_DOCUMENT_VIEW (XGE_ENABLE_XUI && XGE_BUILD_PROFILE != XGE_PROFILE_UI_MIN)
#endif
#ifndef XUI_ENABLE_FILE_DIALOG
#define XUI_ENABLE_FILE_DIALOG (XGE_ENABLE_XUI && XGE_BUILD_PROFILE != XGE_PROFILE_UI_MIN)
#endif
#ifndef XUI_ENABLE_FIND
#define XUI_ENABLE_FIND (XGE_ENABLE_XUI && XGE_BUILD_PROFILE != XGE_PROFILE_UI_MIN)
#endif
#ifndef XUI_ENABLE_FLOW_GRAPH
#define XUI_ENABLE_FLOW_GRAPH (XGE_ENABLE_XUI && XGE_BUILD_PROFILE != XGE_PROFILE_UI_MIN)
#endif
#ifndef XUI_ENABLE_HYPERLINK
#define XUI_ENABLE_HYPERLINK (XGE_ENABLE_XUI && XGE_BUILD_PROFILE != XGE_PROFILE_UI_MIN)
#endif
#ifndef XUI_ENABLE_ICON_PICKER
#define XUI_ENABLE_ICON_PICKER (XGE_ENABLE_XUI && XGE_BUILD_PROFILE != XGE_PROFILE_UI_MIN)
#endif
#ifndef XUI_ENABLE_IMAGE
#define XUI_ENABLE_IMAGE (XGE_ENABLE_XUI)
#endif
#ifndef XUI_ENABLE_INPUT
#define XUI_ENABLE_INPUT (XGE_ENABLE_XUI && XGE_BUILD_PROFILE != XGE_PROFILE_UI_MIN)
#endif
#ifndef XUI_ENABLE_INVENTORY_GRID
#define XUI_ENABLE_INVENTORY_GRID (XGE_ENABLE_XUI && XGE_BUILD_PROFILE != XGE_PROFILE_UI_MIN)
#endif
#ifndef XUI_ENABLE_LABEL
#define XUI_ENABLE_LABEL (XGE_ENABLE_XUI)
#endif
#ifndef XUI_ENABLE_LIST_VIEW
#define XUI_ENABLE_LIST_VIEW (XGE_ENABLE_XUI && XGE_BUILD_PROFILE != XGE_PROFILE_UI_MIN)
#endif
#ifndef XUI_ENABLE_MENU
#define XUI_ENABLE_MENU (XGE_ENABLE_XUI && XGE_BUILD_PROFILE != XGE_PROFILE_UI_MIN)
#endif
#ifndef XUI_ENABLE_MENUBAR
#define XUI_ENABLE_MENUBAR (XGE_ENABLE_XUI && XGE_BUILD_PROFILE != XGE_PROFILE_UI_MIN)
#endif
#ifndef XUI_ENABLE_MESSAGE_LIST
#define XUI_ENABLE_MESSAGE_LIST (XGE_ENABLE_XUI && XGE_BUILD_PROFILE != XGE_PROFILE_UI_MIN)
#endif
#ifndef XUI_ENABLE_MSGBOX
#define XUI_ENABLE_MSGBOX (XGE_ENABLE_XUI && XGE_BUILD_PROFILE != XGE_PROFILE_UI_MIN)
#endif
#ifndef XUI_ENABLE_MSGTIP
#define XUI_ENABLE_MSGTIP (XGE_ENABLE_XUI && XGE_BUILD_PROFILE != XGE_PROFILE_UI_MIN)
#endif
#ifndef XUI_ENABLE_NUMERIC_INPUT
#define XUI_ENABLE_NUMERIC_INPUT (XGE_ENABLE_XUI && XGE_BUILD_PROFILE != XGE_PROFILE_UI_MIN)
#endif
#ifndef XUI_ENABLE_PAGE
#define XUI_ENABLE_PAGE (XGE_ENABLE_XUI && XGE_BUILD_PROFILE != XGE_PROFILE_UI_MIN)
#endif
#ifndef XUI_ENABLE_PANEL
#define XUI_ENABLE_PANEL (XGE_ENABLE_XUI)
#endif
#ifndef XUI_ENABLE_POPUP
#define XUI_ENABLE_POPUP (XGE_ENABLE_XUI && XGE_BUILD_PROFILE != XGE_PROFILE_UI_MIN)
#endif
#ifndef XUI_ENABLE_PROGRESS
#define XUI_ENABLE_PROGRESS (XGE_ENABLE_XUI && XGE_BUILD_PROFILE != XGE_PROFILE_UI_MIN)
#endif
#ifndef XUI_ENABLE_PROPERTY_GRID
#define XUI_ENABLE_PROPERTY_GRID (XGE_ENABLE_XUI && XGE_BUILD_PROFILE != XGE_PROFILE_UI_MIN)
#endif
#ifndef XUI_ENABLE_QRCODE
#define XUI_ENABLE_QRCODE (XGE_ENABLE_XUI && XGE_BUILD_PROFILE != XGE_PROFILE_UI_MIN)
#endif
#ifndef XUI_ENABLE_RADIO
#define XUI_ENABLE_RADIO (XGE_ENABLE_XUI && XGE_BUILD_PROFILE != XGE_PROFILE_UI_MIN)
#endif
#ifndef XUI_ENABLE_RANGE_SLIDER
#define XUI_ENABLE_RANGE_SLIDER (XGE_ENABLE_XUI && XGE_BUILD_PROFILE != XGE_PROFILE_UI_MIN)
#endif
#ifndef XUI_ENABLE_SCROLLBAR
#define XUI_ENABLE_SCROLLBAR (XGE_ENABLE_XUI && XGE_BUILD_PROFILE != XGE_PROFILE_UI_MIN)
#endif
#ifndef XUI_ENABLE_SCROLL_FRAME
#define XUI_ENABLE_SCROLL_FRAME (XGE_ENABLE_XUI && XGE_BUILD_PROFILE != XGE_PROFILE_UI_MIN)
#endif
#ifndef XUI_ENABLE_SCROLL_VIEW
#define XUI_ENABLE_SCROLL_VIEW (XGE_ENABLE_XUI && XGE_BUILD_PROFILE != XGE_PROFILE_UI_MIN)
#endif
#ifndef XUI_ENABLE_SEPARATOR
#define XUI_ENABLE_SEPARATOR (XGE_ENABLE_XUI && XGE_BUILD_PROFILE != XGE_PROFILE_UI_MIN)
#endif
#ifndef XUI_ENABLE_SLIDER
#define XUI_ENABLE_SLIDER (XGE_ENABLE_XUI && XGE_BUILD_PROFILE != XGE_PROFILE_UI_MIN)
#endif
#ifndef XUI_ENABLE_SPLIT_LAYOUT
#define XUI_ENABLE_SPLIT_LAYOUT (XGE_ENABLE_XUI && XGE_BUILD_PROFILE != XGE_PROFILE_UI_MIN)
#endif
#ifndef XUI_ENABLE_STATUSBAR
#define XUI_ENABLE_STATUSBAR (XGE_ENABLE_XUI && XGE_BUILD_PROFILE != XGE_PROFILE_UI_MIN)
#endif
#ifndef XUI_ENABLE_STEP_BAR
#define XUI_ENABLE_STEP_BAR (XGE_ENABLE_XUI && XGE_BUILD_PROFILE != XGE_PROFILE_UI_MIN)
#endif
#ifndef XUI_ENABLE_TABLE_GRID
#define XUI_ENABLE_TABLE_GRID (XGE_ENABLE_XUI && XGE_BUILD_PROFILE != XGE_PROFILE_UI_MIN)
#endif
#ifndef XUI_ENABLE_TABLE_VIEW
#define XUI_ENABLE_TABLE_VIEW (XGE_ENABLE_XUI && XGE_BUILD_PROFILE != XGE_PROFILE_UI_MIN)
#endif
#ifndef XUI_ENABLE_TABS
#define XUI_ENABLE_TABS (XGE_ENABLE_XUI && XGE_BUILD_PROFILE != XGE_PROFILE_UI_MIN)
#endif
#ifndef XUI_ENABLE_TAG_INPUT
#define XUI_ENABLE_TAG_INPUT (XGE_ENABLE_XUI && XGE_BUILD_PROFILE != XGE_PROFILE_UI_MIN)
#endif
#ifndef XUI_ENABLE_TERMINAL
#define XUI_ENABLE_TERMINAL (XGE_ENABLE_XUI && XGE_BUILD_PROFILE != XGE_PROFILE_UI_MIN)
#endif
#ifndef XUI_ENABLE_TEXT_EDIT
#define XUI_ENABLE_TEXT_EDIT (XGE_ENABLE_XUI && XGE_BUILD_PROFILE != XGE_PROFILE_UI_MIN)
#endif
#ifndef XUI_ENABLE_TIMELINE_VIEW
#define XUI_ENABLE_TIMELINE_VIEW (XGE_ENABLE_XUI && XGE_BUILD_PROFILE != XGE_PROFILE_UI_MIN)
#endif
#ifndef XUI_ENABLE_TOAST
#define XUI_ENABLE_TOAST (XGE_ENABLE_XUI && XGE_BUILD_PROFILE != XGE_PROFILE_UI_MIN)
#endif
#ifndef XUI_ENABLE_TOGGLE
#define XUI_ENABLE_TOGGLE (XGE_ENABLE_XUI && XGE_BUILD_PROFILE != XGE_PROFILE_UI_MIN)
#endif
#ifndef XUI_ENABLE_TOOLBAR
#define XUI_ENABLE_TOOLBAR (XGE_ENABLE_XUI && XGE_BUILD_PROFILE != XGE_PROFILE_UI_MIN)
#endif
#ifndef XUI_ENABLE_TREE_VIEW
#define XUI_ENABLE_TREE_VIEW (XGE_ENABLE_XUI && XGE_BUILD_PROFILE != XGE_PROFILE_UI_MIN)
#endif
#ifndef XUI_ENABLE_VIRTUAL_JOYSTICK
#define XUI_ENABLE_VIRTUAL_JOYSTICK (XGE_ENABLE_XUI && XGE_BUILD_PROFILE != XGE_PROFILE_UI_MIN)
#endif
#ifndef XUI_ENABLE_WEBVIEW
#define XUI_ENABLE_WEBVIEW (XGE_ENABLE_XUI && XGE_BUILD_PROFILE != XGE_PROFILE_UI_MIN)
#endif
#ifndef XUI_ENABLE_WINDOW
#define XUI_ENABLE_WINDOW (XGE_ENABLE_XUI && XGE_BUILD_PROFILE != XGE_PROFILE_UI_MIN)
#endif
#ifndef XUI_ENABLE_WORKFLOW
#define XUI_ENABLE_WORKFLOW (XGE_ENABLE_XUI && XGE_BUILD_PROFILE != XGE_PROFILE_UI_MIN)
#endif

#if XUI_ENABLE_DOCUMENT_EDITOR && !XUI_ENABLE_DOCUMENT_VIEW
#error "DocumentEditor requires DocumentView"
#endif
#if XUI_ENABLE_DOCUMENT_VIEW && !XUI_ENABLE_DOCUMENT
#error "DocumentView requires Document"
#endif
#ifndef XUI_ENABLE_RADIO_GROUP
#define XUI_ENABLE_RADIO_GROUP (XUI_ENABLE_RADIO && XGE_BUILD_PROFILE != XGE_PROFILE_UI_MIN)
#endif

/* Actual component dependencies; supply the closure in custom builds. */
#if XUI_ENABLE_CANVAS && !((XUI_ENABLE_SCROLL_FRAME))
#error "XUI_ENABLE_CANVAS has disabled dependencies: XUI_ENABLE_SCROLL_FRAME"
#endif
#if XUI_ENABLE_CASCADER && !((XUI_ENABLE_POPUP))
#error "XUI_ENABLE_CASCADER has disabled dependencies: XUI_ENABLE_POPUP"
#endif
#if XUI_ENABLE_CHECK_CARD && !((XUI_ENABLE_RADIO_GROUP))
#error "XUI_ENABLE_CHECK_CARD has disabled dependencies: XUI_ENABLE_RADIO_GROUP"
#endif
#if XUI_ENABLE_CODE_EDIT && !(((XUI_ENABLE_SCROLLBAR || XUI_ENABLE_SCROLL_FRAME || XUI_ENABLE_SCROLL_VIEW || XUI_ENABLE_TABLE_VIEW || XUI_ENABLE_TREE_VIEW || XUI_ENABLE_LIST_VIEW || XUI_ENABLE_TEXT_EDIT || XUI_ENABLE_CODE_EDIT || XUI_ENABLE_DOCUMENT_VIEW || XUI_ENABLE_TERMINAL)) && (XUI_ENABLE_BUTTON) && (XUI_ENABLE_CHECKBOX) && (XUI_ENABLE_FIND) && (XUI_ENABLE_INPUT) && (XUI_ENABLE_LABEL) && (XUI_ENABLE_LIST_VIEW) && (XUI_ENABLE_MENU) && (XUI_ENABLE_POPUP) && (XUI_ENABLE_SCROLLBAR) && (XUI_ENABLE_TABLE_VIEW) && (XUI_ENABLE_WINDOW))
#error "XUI_ENABLE_CODE_EDIT has disabled dependencies: (XUI_ENABLE_SCROLLBAR || XUI_ENABLE_SCROLL_FRAME || XUI_ENABLE_SCROLL_VIEW || XUI_ENABLE_TABLE_VIEW || XUI_ENABLE_TREE_VIEW || XUI_ENABLE_LIST_VIEW || XUI_ENABLE_TEXT_EDIT || XUI_ENABLE_CODE_EDIT || XUI_ENABLE_DOCUMENT_VIEW || XUI_ENABLE_TERMINAL), XUI_ENABLE_BUTTON, XUI_ENABLE_CHECKBOX, XUI_ENABLE_FIND, XUI_ENABLE_INPUT, XUI_ENABLE_LABEL, XUI_ENABLE_LIST_VIEW, XUI_ENABLE_MENU, XUI_ENABLE_POPUP, XUI_ENABLE_SCROLLBAR, XUI_ENABLE_TABLE_VIEW, XUI_ENABLE_WINDOW"
#endif
#if XUI_ENABLE_COLOR_PICKER && !((XUI_ENABLE_POPUP))
#error "XUI_ENABLE_COLOR_PICKER has disabled dependencies: XUI_ENABLE_POPUP"
#endif
#if XUI_ENABLE_COMBOBOX && !((XUI_ENABLE_INPUT) && (XUI_ENABLE_MENU) && (XUI_ENABLE_POPUP))
#error "XUI_ENABLE_COMBOBOX has disabled dependencies: XUI_ENABLE_INPUT, XUI_ENABLE_MENU, XUI_ENABLE_POPUP"
#endif
#if XUI_ENABLE_DATE_PICKER && !((XUI_ENABLE_POPUP))
#error "XUI_ENABLE_DATE_PICKER has disabled dependencies: XUI_ENABLE_POPUP"
#endif
#if XUI_ENABLE_DOCK_PANEL && !((XUI_ENABLE_MENU) && (XUI_ENABLE_WINDOW))
#error "XUI_ENABLE_DOCK_PANEL has disabled dependencies: XUI_ENABLE_MENU, XUI_ENABLE_WINDOW"
#endif
#if XUI_ENABLE_DOCUMENT_EDITOR && !((XUI_ENABLE_BUTTON) && (XUI_ENABLE_CHECKBOX) && (XUI_ENABLE_DOCUMENT) && (XUI_ENABLE_DOCUMENT_VIEW) && (XUI_ENABLE_INPUT) && (XUI_ENABLE_LABEL) && (XUI_ENABLE_MENU) && (XUI_ENABLE_TABLE_VIEW) && (XUI_ENABLE_TOOLBAR) && (XUI_ENABLE_WINDOW))
#error "XUI_ENABLE_DOCUMENT_EDITOR has disabled dependencies: XUI_ENABLE_BUTTON, XUI_ENABLE_CHECKBOX, XUI_ENABLE_DOCUMENT, XUI_ENABLE_DOCUMENT_VIEW, XUI_ENABLE_INPUT, XUI_ENABLE_LABEL, XUI_ENABLE_MENU, XUI_ENABLE_TABLE_VIEW, XUI_ENABLE_TOOLBAR, XUI_ENABLE_WINDOW"
#endif
#if XUI_ENABLE_DOCUMENT_VIEW && !((XUI_ENABLE_DOCUMENT) && (XUI_ENABLE_DOCUMENT_EDITOR))
#error "XUI_ENABLE_DOCUMENT_VIEW has disabled dependencies: XUI_ENABLE_DOCUMENT, XUI_ENABLE_DOCUMENT_EDITOR"
#endif
#if XUI_ENABLE_FILE_DIALOG && !((XUI_ENABLE_BREADCRUMB) && (XUI_ENABLE_BUTTON) && (XUI_ENABLE_COMBOBOX) && (XUI_ENABLE_INPUT) && (XUI_ENABLE_LABEL) && (XUI_ENABLE_LIST_VIEW) && (XUI_ENABLE_MSGBOX) && (XUI_ENABLE_MSGTIP) && (XUI_ENABLE_WINDOW))
#error "XUI_ENABLE_FILE_DIALOG has disabled dependencies: XUI_ENABLE_BREADCRUMB, XUI_ENABLE_BUTTON, XUI_ENABLE_COMBOBOX, XUI_ENABLE_INPUT, XUI_ENABLE_LABEL, XUI_ENABLE_LIST_VIEW, XUI_ENABLE_MSGBOX, XUI_ENABLE_MSGTIP, XUI_ENABLE_WINDOW"
#endif
#if XUI_ENABLE_ICON_PICKER && !((XUI_ENABLE_POPUP) && (XUI_ENABLE_SCROLL_FRAME) && (XUI_ENABLE_SCROLL_VIEW))
#error "XUI_ENABLE_ICON_PICKER has disabled dependencies: XUI_ENABLE_POPUP, XUI_ENABLE_SCROLL_FRAME, XUI_ENABLE_SCROLL_VIEW"
#endif
#if XUI_ENABLE_INPUT && !((XUI_ENABLE_MENU))
#error "XUI_ENABLE_INPUT has disabled dependencies: XUI_ENABLE_MENU"
#endif
#if XUI_ENABLE_INVENTORY_GRID && !(((XUI_ENABLE_SCROLLBAR || XUI_ENABLE_SCROLL_FRAME || XUI_ENABLE_SCROLL_VIEW || XUI_ENABLE_TABLE_VIEW || XUI_ENABLE_TREE_VIEW || XUI_ENABLE_LIST_VIEW || XUI_ENABLE_TEXT_EDIT || XUI_ENABLE_CODE_EDIT || XUI_ENABLE_DOCUMENT_VIEW || XUI_ENABLE_TERMINAL)) && (XUI_ENABLE_BUTTON) && (XUI_ENABLE_LABEL) && (XUI_ENABLE_NUMERIC_INPUT) && (XUI_ENABLE_POPUP))
#error "XUI_ENABLE_INVENTORY_GRID has disabled dependencies: (XUI_ENABLE_SCROLLBAR || XUI_ENABLE_SCROLL_FRAME || XUI_ENABLE_SCROLL_VIEW || XUI_ENABLE_TABLE_VIEW || XUI_ENABLE_TREE_VIEW || XUI_ENABLE_LIST_VIEW || XUI_ENABLE_TEXT_EDIT || XUI_ENABLE_CODE_EDIT || XUI_ENABLE_DOCUMENT_VIEW || XUI_ENABLE_TERMINAL), XUI_ENABLE_BUTTON, XUI_ENABLE_LABEL, XUI_ENABLE_NUMERIC_INPUT, XUI_ENABLE_POPUP"
#endif
#if XUI_ENABLE_LIST_VIEW && !((XUI_ENABLE_SCROLL_FRAME))
#error "XUI_ENABLE_LIST_VIEW has disabled dependencies: XUI_ENABLE_SCROLL_FRAME"
#endif
#if XUI_ENABLE_MENU && !((XUI_ENABLE_POPUP))
#error "XUI_ENABLE_MENU has disabled dependencies: XUI_ENABLE_POPUP"
#endif
#if XUI_ENABLE_MENUBAR && !((XUI_ENABLE_MENU) && (XUI_ENABLE_POPUP))
#error "XUI_ENABLE_MENUBAR has disabled dependencies: XUI_ENABLE_MENU, XUI_ENABLE_POPUP"
#endif
#if XUI_ENABLE_MESSAGE_LIST && !((XUI_ENABLE_DOCUMENT) && (XUI_ENABLE_DOCUMENT_EDITOR) && (XUI_ENABLE_DOCUMENT_VIEW) && (XUI_ENABLE_MENU))
#error "XUI_ENABLE_MESSAGE_LIST has disabled dependencies: XUI_ENABLE_DOCUMENT, XUI_ENABLE_DOCUMENT_EDITOR, XUI_ENABLE_DOCUMENT_VIEW, XUI_ENABLE_MENU"
#endif
#if XUI_ENABLE_MSGBOX && !((XUI_ENABLE_BUTTON) && (XUI_ENABLE_WINDOW))
#error "XUI_ENABLE_MSGBOX has disabled dependencies: XUI_ENABLE_BUTTON, XUI_ENABLE_WINDOW"
#endif
#if XUI_ENABLE_NUMERIC_INPUT && !((XUI_ENABLE_INPUT))
#error "XUI_ENABLE_NUMERIC_INPUT has disabled dependencies: XUI_ENABLE_INPUT"
#endif
#if XUI_ENABLE_PANEL && !((XUI_ENABLE_IMAGE) && (XUI_ENABLE_LABEL))
#error "XUI_ENABLE_PANEL has disabled dependencies: XUI_ENABLE_IMAGE, XUI_ENABLE_LABEL"
#endif
#if XUI_ENABLE_POPUP && !((XUI_ENABLE_SCROLL_VIEW))
#error "XUI_ENABLE_POPUP has disabled dependencies: XUI_ENABLE_SCROLL_VIEW"
#endif
#if XUI_ENABLE_PROPERTY_GRID && !((XUI_ENABLE_SCROLL_FRAME) && (XUI_ENABLE_TABLE_GRID) && (XUI_ENABLE_TABLE_VIEW))
#error "XUI_ENABLE_PROPERTY_GRID has disabled dependencies: XUI_ENABLE_SCROLL_FRAME, XUI_ENABLE_TABLE_GRID, XUI_ENABLE_TABLE_VIEW"
#endif
#if XUI_ENABLE_RADIO_GROUP && !((XUI_ENABLE_CHECK_CARD) && (XUI_ENABLE_RADIO))
#error "XUI_ENABLE_RADIO_GROUP has disabled dependencies: XUI_ENABLE_CHECK_CARD, XUI_ENABLE_RADIO"
#endif
#if XUI_ENABLE_SCROLL_FRAME && !(((XUI_ENABLE_SCROLLBAR || XUI_ENABLE_SCROLL_FRAME || XUI_ENABLE_SCROLL_VIEW || XUI_ENABLE_TABLE_VIEW || XUI_ENABLE_TREE_VIEW || XUI_ENABLE_LIST_VIEW || XUI_ENABLE_TEXT_EDIT || XUI_ENABLE_CODE_EDIT || XUI_ENABLE_DOCUMENT_VIEW || XUI_ENABLE_TERMINAL)) && (XUI_ENABLE_SCROLLBAR))
#error "XUI_ENABLE_SCROLL_FRAME has disabled dependencies: (XUI_ENABLE_SCROLLBAR || XUI_ENABLE_SCROLL_FRAME || XUI_ENABLE_SCROLL_VIEW || XUI_ENABLE_TABLE_VIEW || XUI_ENABLE_TREE_VIEW || XUI_ENABLE_LIST_VIEW || XUI_ENABLE_TEXT_EDIT || XUI_ENABLE_CODE_EDIT || XUI_ENABLE_DOCUMENT_VIEW || XUI_ENABLE_TERMINAL), XUI_ENABLE_SCROLLBAR"
#endif
#if XUI_ENABLE_SCROLL_VIEW && !((XUI_ENABLE_SCROLL_FRAME))
#error "XUI_ENABLE_SCROLL_VIEW has disabled dependencies: XUI_ENABLE_SCROLL_FRAME"
#endif
#if XUI_ENABLE_TABLE_GRID && !((XUI_ENABLE_BUTTON) && (XUI_ENABLE_COLOR_PICKER) && (XUI_ENABLE_COMBOBOX) && (XUI_ENABLE_DATE_PICKER) && (XUI_ENABLE_INPUT) && (XUI_ENABLE_NUMERIC_INPUT) && (XUI_ENABLE_POPUP) && (XUI_ENABLE_SCROLL_FRAME) && (XUI_ENABLE_TABLE_VIEW) && (XUI_ENABLE_TEXT_EDIT))
#error "XUI_ENABLE_TABLE_GRID has disabled dependencies: XUI_ENABLE_BUTTON, XUI_ENABLE_COLOR_PICKER, XUI_ENABLE_COMBOBOX, XUI_ENABLE_DATE_PICKER, XUI_ENABLE_INPUT, XUI_ENABLE_NUMERIC_INPUT, XUI_ENABLE_POPUP, XUI_ENABLE_SCROLL_FRAME, XUI_ENABLE_TABLE_VIEW, XUI_ENABLE_TEXT_EDIT"
#endif
#if XUI_ENABLE_TABLE_VIEW && !((XUI_ENABLE_SCROLL_FRAME))
#error "XUI_ENABLE_TABLE_VIEW has disabled dependencies: XUI_ENABLE_SCROLL_FRAME"
#endif
#if XUI_ENABLE_TABS && !((XUI_ENABLE_MENU))
#error "XUI_ENABLE_TABS has disabled dependencies: XUI_ENABLE_MENU"
#endif
#if XUI_ENABLE_TAG_INPUT && !((XUI_ENABLE_INPUT))
#error "XUI_ENABLE_TAG_INPUT has disabled dependencies: XUI_ENABLE_INPUT"
#endif
#if XUI_ENABLE_TERMINAL && !(((XUI_ENABLE_SCROLLBAR || XUI_ENABLE_SCROLL_FRAME || XUI_ENABLE_SCROLL_VIEW || XUI_ENABLE_TABLE_VIEW || XUI_ENABLE_TREE_VIEW || XUI_ENABLE_LIST_VIEW || XUI_ENABLE_TEXT_EDIT || XUI_ENABLE_CODE_EDIT || XUI_ENABLE_DOCUMENT_VIEW || XUI_ENABLE_TERMINAL)) && (XUI_ENABLE_BUTTON) && (XUI_ENABLE_CHECKBOX) && (XUI_ENABLE_FIND) && (XUI_ENABLE_INPUT) && (XUI_ENABLE_LABEL) && (XUI_ENABLE_MENU) && (XUI_ENABLE_WINDOW))
#error "XUI_ENABLE_TERMINAL has disabled dependencies: (XUI_ENABLE_SCROLLBAR || XUI_ENABLE_SCROLL_FRAME || XUI_ENABLE_SCROLL_VIEW || XUI_ENABLE_TABLE_VIEW || XUI_ENABLE_TREE_VIEW || XUI_ENABLE_LIST_VIEW || XUI_ENABLE_TEXT_EDIT || XUI_ENABLE_CODE_EDIT || XUI_ENABLE_DOCUMENT_VIEW || XUI_ENABLE_TERMINAL), XUI_ENABLE_BUTTON, XUI_ENABLE_CHECKBOX, XUI_ENABLE_FIND, XUI_ENABLE_INPUT, XUI_ENABLE_LABEL, XUI_ENABLE_MENU, XUI_ENABLE_WINDOW"
#endif
#if XUI_ENABLE_TEXT_EDIT && !(((XUI_ENABLE_SCROLLBAR || XUI_ENABLE_SCROLL_FRAME || XUI_ENABLE_SCROLL_VIEW || XUI_ENABLE_TABLE_VIEW || XUI_ENABLE_TREE_VIEW || XUI_ENABLE_LIST_VIEW || XUI_ENABLE_TEXT_EDIT || XUI_ENABLE_CODE_EDIT || XUI_ENABLE_DOCUMENT_VIEW || XUI_ENABLE_TERMINAL)) && (XUI_ENABLE_BUTTON) && (XUI_ENABLE_CHECKBOX) && (XUI_ENABLE_FIND) && (XUI_ENABLE_INPUT) && (XUI_ENABLE_LABEL) && (XUI_ENABLE_MENU) && (XUI_ENABLE_SCROLLBAR) && (XUI_ENABLE_WINDOW))
#error "XUI_ENABLE_TEXT_EDIT has disabled dependencies: (XUI_ENABLE_SCROLLBAR || XUI_ENABLE_SCROLL_FRAME || XUI_ENABLE_SCROLL_VIEW || XUI_ENABLE_TABLE_VIEW || XUI_ENABLE_TREE_VIEW || XUI_ENABLE_LIST_VIEW || XUI_ENABLE_TEXT_EDIT || XUI_ENABLE_CODE_EDIT || XUI_ENABLE_DOCUMENT_VIEW || XUI_ENABLE_TERMINAL), XUI_ENABLE_BUTTON, XUI_ENABLE_CHECKBOX, XUI_ENABLE_FIND, XUI_ENABLE_INPUT, XUI_ENABLE_LABEL, XUI_ENABLE_MENU, XUI_ENABLE_SCROLLBAR, XUI_ENABLE_WINDOW"
#endif
#if XUI_ENABLE_TIMELINE_VIEW && !((XUI_ENABLE_MENU) && (XUI_ENABLE_SCROLL_FRAME))
#error "XUI_ENABLE_TIMELINE_VIEW has disabled dependencies: XUI_ENABLE_MENU, XUI_ENABLE_SCROLL_FRAME"
#endif
#if XUI_ENABLE_TREE_VIEW && !((XUI_ENABLE_SCROLL_FRAME))
#error "XUI_ENABLE_TREE_VIEW has disabled dependencies: XUI_ENABLE_SCROLL_FRAME"
#endif
#if XUI_ENABLE_WEBVIEW && !((XUI_ENABLE_DOCUMENT) && (XUI_ENABLE_WINDOW))
#error "XUI_ENABLE_WEBVIEW has disabled dependencies: XUI_ENABLE_DOCUMENT, XUI_ENABLE_WINDOW"
#endif
#if XUI_ENABLE_WORKFLOW && !((XUI_ENABLE_FLOW_GRAPH))
#error "XUI_ENABLE_WORKFLOW has disabled dependencies: XUI_ENABLE_FLOW_GRAPH"
#endif

#if (XUI_ENABLE_ACCORDION != 0 && XUI_ENABLE_ACCORDION != 1) || (XUI_ENABLE_BREADCRUMB != 0 && XUI_ENABLE_BREADCRUMB != 1) || (XUI_ENABLE_BUTTON != 0 && XUI_ENABLE_BUTTON != 1) || (XUI_ENABLE_CANVAS != 0 && XUI_ENABLE_CANVAS != 1) || (XUI_ENABLE_CAROUSEL != 0 && XUI_ENABLE_CAROUSEL != 1) || (XUI_ENABLE_CASCADER != 0 && XUI_ENABLE_CASCADER != 1) || (XUI_ENABLE_CHART != 0 && XUI_ENABLE_CHART != 1) || (XUI_ENABLE_CHECKBOX != 0 && XUI_ENABLE_CHECKBOX != 1) || (XUI_ENABLE_CHECK_CARD != 0 && XUI_ENABLE_CHECK_CARD != 1) || (XUI_ENABLE_CODE_EDIT != 0 && XUI_ENABLE_CODE_EDIT != 1) || (XUI_ENABLE_COLOR_PICKER != 0 && XUI_ENABLE_COLOR_PICKER != 1) || (XUI_ENABLE_COMBOBOX != 0 && XUI_ENABLE_COMBOBOX != 1) || (XUI_ENABLE_DATE_PICKER != 0 && XUI_ENABLE_DATE_PICKER != 1) || (XUI_ENABLE_DOCK_PANEL != 0 && XUI_ENABLE_DOCK_PANEL != 1) || (XUI_ENABLE_DOCUMENT != 0 && XUI_ENABLE_DOCUMENT != 1) || (XUI_ENABLE_DOCUMENT_EDITOR != 0 && XUI_ENABLE_DOCUMENT_EDITOR != 1) || (XUI_ENABLE_DOCUMENT_VIEW != 0 && XUI_ENABLE_DOCUMENT_VIEW != 1) || (XUI_ENABLE_FILE_DIALOG != 0 && XUI_ENABLE_FILE_DIALOG != 1) || (XUI_ENABLE_FIND != 0 && XUI_ENABLE_FIND != 1) || (XUI_ENABLE_FLOW_GRAPH != 0 && XUI_ENABLE_FLOW_GRAPH != 1) || (XUI_ENABLE_HYPERLINK != 0 && XUI_ENABLE_HYPERLINK != 1) || (XUI_ENABLE_ICON_PICKER != 0 && XUI_ENABLE_ICON_PICKER != 1) || (XUI_ENABLE_IMAGE != 0 && XUI_ENABLE_IMAGE != 1) || (XUI_ENABLE_INPUT != 0 && XUI_ENABLE_INPUT != 1) || (XUI_ENABLE_INVENTORY_GRID != 0 && XUI_ENABLE_INVENTORY_GRID != 1) || (XUI_ENABLE_LABEL != 0 && XUI_ENABLE_LABEL != 1) || (XUI_ENABLE_LIST_VIEW != 0 && XUI_ENABLE_LIST_VIEW != 1) || (XUI_ENABLE_MENU != 0 && XUI_ENABLE_MENU != 1) || (XUI_ENABLE_MENUBAR != 0 && XUI_ENABLE_MENUBAR != 1) || (XUI_ENABLE_MESSAGE_LIST != 0 && XUI_ENABLE_MESSAGE_LIST != 1) || (XUI_ENABLE_MSGBOX != 0 && XUI_ENABLE_MSGBOX != 1) || (XUI_ENABLE_MSGTIP != 0 && XUI_ENABLE_MSGTIP != 1) || (XUI_ENABLE_NUMERIC_INPUT != 0 && XUI_ENABLE_NUMERIC_INPUT != 1) || (XUI_ENABLE_PAGE != 0 && XUI_ENABLE_PAGE != 1) || (XUI_ENABLE_PANEL != 0 && XUI_ENABLE_PANEL != 1) || (XUI_ENABLE_POPUP != 0 && XUI_ENABLE_POPUP != 1) || (XUI_ENABLE_PROGRESS != 0 && XUI_ENABLE_PROGRESS != 1) || (XUI_ENABLE_PROPERTY_GRID != 0 && XUI_ENABLE_PROPERTY_GRID != 1) || (XUI_ENABLE_QRCODE != 0 && XUI_ENABLE_QRCODE != 1) || (XUI_ENABLE_RADIO != 0 && XUI_ENABLE_RADIO != 1) || (XUI_ENABLE_RADIO_GROUP != 0 && XUI_ENABLE_RADIO_GROUP != 1) || (XUI_ENABLE_RANGE_SLIDER != 0 && XUI_ENABLE_RANGE_SLIDER != 1) || (XUI_ENABLE_SCROLLBAR != 0 && XUI_ENABLE_SCROLLBAR != 1) || (XUI_ENABLE_SCROLL_FRAME != 0 && XUI_ENABLE_SCROLL_FRAME != 1) || (XUI_ENABLE_SCROLL_VIEW != 0 && XUI_ENABLE_SCROLL_VIEW != 1) || (XUI_ENABLE_SEPARATOR != 0 && XUI_ENABLE_SEPARATOR != 1) || (XUI_ENABLE_SLIDER != 0 && XUI_ENABLE_SLIDER != 1) || (XUI_ENABLE_SPLIT_LAYOUT != 0 && XUI_ENABLE_SPLIT_LAYOUT != 1) || (XUI_ENABLE_STATUSBAR != 0 && XUI_ENABLE_STATUSBAR != 1) || (XUI_ENABLE_STEP_BAR != 0 && XUI_ENABLE_STEP_BAR != 1) || (XUI_ENABLE_TABLE_GRID != 0 && XUI_ENABLE_TABLE_GRID != 1) || (XUI_ENABLE_TABLE_VIEW != 0 && XUI_ENABLE_TABLE_VIEW != 1) || (XUI_ENABLE_TABS != 0 && XUI_ENABLE_TABS != 1) || (XUI_ENABLE_TAG_INPUT != 0 && XUI_ENABLE_TAG_INPUT != 1) || (XUI_ENABLE_TERMINAL != 0 && XUI_ENABLE_TERMINAL != 1) || (XUI_ENABLE_TEXT_EDIT != 0 && XUI_ENABLE_TEXT_EDIT != 1) || (XUI_ENABLE_TIMELINE_VIEW != 0 && XUI_ENABLE_TIMELINE_VIEW != 1) || (XUI_ENABLE_TOAST != 0 && XUI_ENABLE_TOAST != 1) || (XUI_ENABLE_TOGGLE != 0 && XUI_ENABLE_TOGGLE != 1) || (XUI_ENABLE_TOOLBAR != 0 && XUI_ENABLE_TOOLBAR != 1) || (XUI_ENABLE_TREE_VIEW != 0 && XUI_ENABLE_TREE_VIEW != 1) || (XUI_ENABLE_VIRTUAL_JOYSTICK != 0 && XUI_ENABLE_VIRTUAL_JOYSTICK != 1) || (XUI_ENABLE_WEBVIEW != 0 && XUI_ENABLE_WEBVIEW != 1) || (XUI_ENABLE_WINDOW != 0 && XUI_ENABLE_WINDOW != 1) || (XUI_ENABLE_WORKFLOW != 0 && XUI_ENABLE_WORKFLOW != 1)
#error "XUI feature switches must be 0 or 1"
#endif
#endif
