#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "zstd.h"
#include "../../lib/stb/stb_image.h"

#include <stdint.h>

#define XUI_ATLAS_ZSTD_LEVEL 19

static int WriteBytes(FILE* pFile, const unsigned char* pData, size_t iSize)
{
	size_t i;

	for ( i = 0; i < iSize; i += 12u ) {
		size_t j;
		size_t iCount = (iSize - i < 12u) ? iSize - i : 12u;
		if ( fputs("\t", pFile) < 0 ) return 0;
		for ( j = 0; j < iCount; j++ ) {
			if ( fprintf(pFile, "%s0x%02x", (j != 0u) ? ", " : "", pData[i + j]) < 0 ) return 0;
		}
		if ( i + iCount < iSize && fputc(',', pFile) == EOF ) return 0;
		if ( fputc('\n', pFile) == EOF ) return 0;
	}
	return 1;
}

static int WriteSource(const char* sPath, int iWidth, int iHeight,
	const unsigned char* pCompressed, size_t iCompressedSize)
{
	char* sTemporary;
	FILE* pFile;
	size_t iPathSize;
	int bOk;

	iPathSize = strlen(sPath);
	sTemporary = (char*)malloc(iPathSize + 5u);
	if ( sTemporary == NULL ) return 0;
	memcpy(sTemporary, sPath, iPathSize);
	memcpy(sTemporary + iPathSize, ".tmp", 5u);
	pFile = fopen(sTemporary, "wb");
	if ( pFile == NULL ) {
		free(sTemporary);
		return 0;
	}
	bOk = fprintf(pFile,
		"/* Auto-generated by tools/xui_asset_atlas/xui_asset_atlas.c. Do not edit. */\n"
		"#include \"xui_builtin_atlas.h\"\n\n"
		"const int g_iXuiBuiltinAtlasWidth = %d;\n"
		"const int g_iXuiBuiltinAtlasHeight = %d;\n"
		"const int g_iXuiBuiltinAtlasStride = %d;\n"
		"const int g_iXuiBuiltinAtlasRgbaSize = %d;\n\n"
		"const unsigned char g_arrXuiBuiltinAtlasRgbaZstd[] = {\n",
		iWidth, iHeight, iWidth * 4, iWidth * iHeight * 4) > 0;
	if ( bOk ) bOk = WriteBytes(pFile, pCompressed, iCompressedSize);
	if ( bOk ) {
		bOk = fprintf(pFile,
			"};\n"
			"const int g_iXuiBuiltinAtlasRgbaZstdSize = "
			"(int)sizeof(g_arrXuiBuiltinAtlasRgbaZstd);\n") > 0;
	}
	if ( fclose(pFile) != 0 ) bOk = 0;
	if ( bOk ) {
		remove(sPath);
		bOk = (rename(sTemporary, sPath) == 0);
	}
	if ( !bOk ) remove(sTemporary);
	free(sTemporary);
	return bOk;
}

static void PremultiplyRGBA(unsigned char* pPixels, size_t iPixelCount)
{
	size_t i;

	for ( i = 0; i < iPixelCount; i++ ) {
		unsigned char* pPixel = pPixels + (i * 4u);
		unsigned int iAlpha = pPixel[3];
		pPixel[0] = (unsigned char)(((unsigned int)pPixel[0] * iAlpha + 127u) / 255u);
		pPixel[1] = (unsigned char)(((unsigned int)pPixel[1] * iAlpha + 127u) / 255u);
		pPixel[2] = (unsigned char)(((unsigned int)pPixel[2] * iAlpha + 127u) / 255u);
	}
}

int main(int argc, char** argv)
{
	unsigned char* pPixels;
	unsigned char* pCompressed;
	unsigned char* pDecoded;
	ZSTD_CCtx* pContext;
	size_t iPixelSize;
	size_t iBound;
	size_t iCompressedSize;
	size_t iDecodedSize;
	int iWidth;
	int iHeight;
	int iChannels;
	int iResult;

	if ( argc != 3 ) {
		fprintf(stderr, "Usage: %s <atlas.png> <output.c>\n", argv[0]);
		return 2;
	}
	pPixels = stbi_load(argv[1], &iWidth, &iHeight, &iChannels, 4);
	if ( pPixels == NULL || iWidth <= 0 || iHeight <= 0 ||
		(size_t)iWidth > SIZE_MAX / 4u / (size_t)iHeight ) {
		fprintf(stderr, "Unable to load RGBA PNG: %s\n", argv[1]);
		stbi_image_free(pPixels);
		return 1;
	}
	iPixelSize = (size_t)iWidth * (size_t)iHeight * 4u;
	if ( iPixelSize > (size_t)INT32_MAX ) {
		fprintf(stderr, "Atlas is too large: %dx%d\n", iWidth, iHeight);
		stbi_image_free(pPixels);
		return 1;
	}
	PremultiplyRGBA(pPixels, (size_t)iWidth * (size_t)iHeight);
	iBound = ZSTD_compressBound(iPixelSize);
	pCompressed = (unsigned char*)malloc(iBound);
	pDecoded = (unsigned char*)malloc(iPixelSize);
	pContext = ZSTD_createCCtx();
	if ( pCompressed == NULL || pDecoded == NULL || pContext == NULL ) {
		fprintf(stderr, "Out of memory\n");
		stbi_image_free(pPixels);
		free(pCompressed);
		free(pDecoded);
		ZSTD_freeCCtx(pContext);
		return 1;
	}
	ZSTD_CCtx_setParameter(pContext, ZSTD_c_compressionLevel, XUI_ATLAS_ZSTD_LEVEL);
	ZSTD_CCtx_setParameter(pContext, ZSTD_c_checksumFlag, 0);
	ZSTD_CCtx_setParameter(pContext, ZSTD_c_contentSizeFlag, 1);
	ZSTD_CCtx_setParameter(pContext, ZSTD_c_dictIDFlag, 0);
	iCompressedSize = ZSTD_compress2(pContext, pCompressed, iBound, pPixels, iPixelSize);
	if ( ZSTD_isError(iCompressedSize) ) {
		fprintf(stderr, "Zstd compression failed: %s\n", ZSTD_getErrorName(iCompressedSize));
		iResult = 1;
	} else {
		iDecodedSize = ZSTD_decompress(pDecoded, iPixelSize, pCompressed, iCompressedSize);
		if ( ZSTD_isError(iDecodedSize) || iDecodedSize != iPixelSize ||
			memcmp(pDecoded, pPixels, iPixelSize) != 0 ) {
			fprintf(stderr, "Zstd round-trip verification failed\n");
			iResult = 1;
		} else if ( !WriteSource(argv[2], iWidth, iHeight, pCompressed, iCompressedSize) ) {
			fprintf(stderr, "Unable to write C source: %s\n", argv[2]);
			iResult = 1;
		} else {
			printf("atlas=%dx%d rgba=%zu zstd=%zu output=%s\n",
				iWidth, iHeight, iPixelSize, iCompressedSize, argv[2]);
			iResult = 0;
		}
	}
	ZSTD_freeCCtx(pContext);
	free(pDecoded);
	free(pCompressed);
	stbi_image_free(pPixels);
	return iResult;
}
