#!/usr/bin/env python3
"""Build XGE's embedded independently-compressed Emoji package."""

from __future__ import annotations

import argparse
import hashlib
import struct
import zlib
from pathlib import Path

import zstandard as zstd


MAGIC = b"XGEMOJI\0"
VERSION = 1
HEADER = struct.Struct("<8s15I")
ENTRY = struct.Struct("<6I")
ZSTD_LEVEL = 19
DICT_SIZE = 32768


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument("--dataset", required=True, type=Path)
    parser.add_argument("--output-bin", required=True, type=Path)
    parser.add_argument("--output-inc", required=True, type=Path)
    parser.add_argument("--dict", dest="dictionary", type=Path)
    return parser.parse_args()


def encode_sequence(text: str) -> bytes:
    return "".join(chr(int(item, 16)) for item in text.split()).encode("utf-8")


def emit_c_array(path: Path, data: bytes) -> None:
    lines = ["/* Generated by tools/emoji_pack/build_builtin_pack.py. */", ""]
    lines.append("static const unsigned char g_xgeBuiltinEmojiPackage[] = {")
    for offset in range(0, len(data), 16):
        chunk = data[offset : offset + 16]
        suffix = "," if offset + 16 < len(data) else ""
        lines.append("\t" + ", ".join(f"0x{value:02x}" for value in chunk) + suffix)
    lines.extend(["};", ""])
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines), encoding="ascii", newline="\n")


def main() -> int:
    args = parse_args()
    manifest = args.dataset / "manifest.txt"
    records: list[tuple[bytes, bytes, int]] = []
    samples: list[bytes] = []
    for line in manifest.read_text(encoding="utf-8").splitlines():
        if not line:
            continue
        fields = line.split("|", 4)
        sequence = encode_sequence(fields[0])
        svg = (args.dataset / "svg" / fields[1]).read_bytes()
        # Fully-qualified text-default sequences already contain VS16. The
        # runtime creates VS16-free aliases with TEXT_DEFAULT semantics.
        flags = 0
        records.append((sequence, svg, flags))
        samples.append(svg)

    if len(records) != 1923:
        raise RuntimeError(f"expected 1923 records, found {len(records)}")
    dictionary = (
        args.dictionary.read_bytes()
        if args.dictionary is not None
        else zstd.train_dictionary(DICT_SIZE, samples).as_bytes()
    )
    if len(dictionary) != DICT_SIZE:
        raise RuntimeError(f"expected {DICT_SIZE}-byte dictionary")
    zdict = zstd.ZstdCompressionDict(dictionary)
    compressor = zstd.ZstdCompressor(
        level=ZSTD_LEVEL,
        dict_data=zdict,
        write_checksum=False,
        write_content_size=False,
        write_dict_id=False,
    )
    decompressor = zstd.ZstdDecompressor(dict_data=zdict)

    sequences = bytearray()
    payload = bytearray()
    index = bytearray()
    for sequence, svg, flags in records:
        sequence_offset = len(sequences)
        sequences.extend(sequence)
        compressed = compressor.compress(svg)
        if decompressor.decompress(compressed, max_output_size=len(svg)) != svg:
            raise RuntimeError("Zstandard round trip failed")
        payload_offset = len(payload)
        payload.extend(compressed)
        index.extend(
            ENTRY.pack(
                sequence_offset,
                len(sequence),
                payload_offset,
                len(compressed),
                len(svg),
                flags,
            )
        )

    header_size = HEADER.size
    index_offset = header_size
    sequence_offset = index_offset + len(index)
    dictionary_offset = sequence_offset + len(sequences)
    payload_offset = dictionary_offset + len(dictionary)
    body = bytes(index + sequences + dictionary + payload)
    package_crc = zlib.crc32(body) & 0xFFFFFFFF
    header = HEADER.pack(
        MAGIC,
        VERSION,
        header_size,
        len(records),
        ENTRY.size,
        index_offset,
        sequence_offset,
        len(sequences),
        dictionary_offset,
        len(dictionary),
        payload_offset,
        len(payload),
        package_crc,
        17,
        0,
        0,
    )
    package = header + body
    args.output_bin.parent.mkdir(parents=True, exist_ok=True)
    args.output_bin.write_bytes(package)
    emit_c_array(args.output_inc, package)
    print(
        f"entries={len(records)} package={len(package)} payload={len(payload)} "
        f"sha256={hashlib.sha256(package).hexdigest()}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
