const fs = require("fs");
const path = require("path");

const root = path.resolve(__dirname, "..", "..");
const assetDir = path.join(root, "res", "emoji", "twemoji");
const manifestPath = path.join(assetDir, "manifest.txt");
const outputPath = path.join(root, "src", "xge_builtin_emoji.inc");

function utf8Bytes(sequence) {
    const text = sequence
        .trim()
        .split(/\s+/)
        .map((value) => String.fromCodePoint(parseInt(value, 16)))
        .join("");
    return Buffer.from(text, "utf8");
}

function emitBytes(name, bytes) {
    const lines = [];
    lines.push(`static const unsigned char ${name}[] = {`);
    for (let offset = 0; offset < bytes.length; offset += 16) {
        const chunk = Array.from(bytes.subarray(offset, offset + 16));
        lines.push(`\t${chunk.map((value) => `0x${value.toString(16).padStart(2, "0")}`).join(", ")}${offset + 16 < bytes.length ? "," : ""}`);
    }
    lines.push("};");
    return lines.join("\n");
}

const records = fs.readFileSync(manifestPath, "utf8")
    .split(/\r?\n/)
    .map((line) => line.trim())
    .filter((line) => line && !line.startsWith("#"))
    .map((line, index) => {
        const [sequence, file, flagsText] = line.split("|").map((part) => part.trim());
        return {
            index,
            sequence: utf8Bytes(sequence),
            svg: fs.readFileSync(path.join(assetDir, file)),
            flags: Number(flagsText || "0"),
        };
    });

const output = [];
output.push("/* Generated by tools/emoji_pack/generate_builtin.js. */");
output.push("");
for (const record of records) {
    output.push(emitBytes(`g_xgeBuiltinEmojiSequence${record.index}`, record.sequence));
    output.push(emitBytes(`g_xgeBuiltinEmojiSvg${record.index}`, record.svg));
    output.push("");
}
output.push("static const xge_builtin_emoji_source_t g_xgeBuiltinEmojiSources[] = {");
for (const record of records) {
    output.push(
        `\t{g_xgeBuiltinEmojiSequence${record.index}, (int)sizeof(g_xgeBuiltinEmojiSequence${record.index}), ` +
        `g_xgeBuiltinEmojiSvg${record.index}, (int)sizeof(g_xgeBuiltinEmojiSvg${record.index}), ${record.flags}u},`
    );
}
output.push("};");
output.push("");

fs.writeFileSync(outputPath, output.join("\n"));
console.log(`generated ${path.relative(root, outputPath)} with ${records.length} entries`);
